name: Build and Unit Test

on:
  pull_request:
    types: [opened, synchronize] # Types added to keep PR status on built pages up to date
  push:
    branches:
      - develop
      - gh-workflow
  workflow_dispatch:

jobs:

  build-and-test:
    runs-on: [ ubuntu-latest]
    container:
      image: ghcr.io/cott81/basic_dev_setup/base-build:dev-latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      options: --user root
    
    strategy:
      fail-fast: false
      matrix:
        variant: [variantX, variantY]

    steps:

      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          persist-credentials: true
          submodules: recursive
          set-safe-directory: true
          token: ${{ secrets.BDC_GITHUB_TOKEN_TEMP }}      

      - name: Set safe directory
        run: git config --global --add safe.directory '/__w/cott81/basic_dev_setup'
        shell: bash

      - name: Configure basic_dev_setup as ${{ matrix.variant }} variant
        run: cmake --preset ${{ matrix.variant }}-x86-64
        shell: bash

      - name: Build basic_dev_setup ${{ matrix.variant }} variant
        run: cmake --build build/${{ matrix.variant }}/x86/
        shell: bash        

      - name: Run Unit Tests for ${{ matrix.variant }}
        run: cd build/${{ matrix.variant }}/x86 && ctest -j $(nproc) --output-on-failure --progress
        shell: bash

  build-documentation:
    runs-on: [ ubuntu-latest]
    container:
      image: ghcr.io/cott81/basic_dev_setup/base-build:dev-latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
      options: --user root

    steps:

      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          persist-credentials: true
          submodules: recursive
          set-safe-directory: true
          token: ${{ secrets.BDC_GITHUB_TOKEN_TEMP }}      

      - name: Set safe directory
        run: git config --global --add safe.directory '/__w/basic_dev_setup/basic_dev_setup'
        shell: bash

      - name: Build Documentation
        run: uv run sphinx-build -j $(nproc) -b html . ./build-docs -c ./docs/ -W && cp docs/_static/index_with_redirect.html build-docs/index.html
        shell: bash
