# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: 
      - develop
      - page-deploy-workflow

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:


  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/cott81/basic_dev_setup/base-build:dev-latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GH_TOKEN }}
      options: --user root    
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          persist-credentials: true
          submodules: recursive
          set-safe-directory: true
          token: ${{ secrets.GH_TOKEN }}

      - name: Set safe directory
        run: git config --global --add safe.directory '/__w/BasicDevSetup/BasicDevSetup'
        shell: bash

      - name: Build Documentation
        run: uv run sphinx-build -j $(nproc) -b html . ./build-docs -c ./docs/ -W && cp docs/_static/index_with_redirect.html build-docs/index.html
        shell: bash

      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: 'build-docs'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4